server:
  port: 8083
spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  rabbitmq:
    host: 169.56.115.175
    username: pubService
    password: '!!pubpub!!'
    port: 5672
    virtualHost: vas
  cloud:
    stream:
      defaultBinder: kafka
      kafka:
        bindings:
          vasRstAi:
            consumer:
              destinationIsPattern: true
        binder:
          brokers: 169.56.76.185:19092, 169.56.76.178:19092, 169.56.76.190:19092
          configuration:
            auto:
              offset:
                reset: latest
            metadata:
              max:
                age:
                  ms: 5000
            key:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bindings:
        vasLog:
          destination: vas_log
          contentType: application/json
        vasRstAi:
          destination: vas_rst_ai_.*
          group: PICK_RST_AI_TEST_2021
          contentType: application/json
        vasNotifyAi:
          destination: vas_notify_ai
          group: PICK_NOTIFY_AI_TEST_2021
          contentType: application/json
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://169.56.76.183:5432/aiden_cloud
    username: visionai
    password: '!skcc1234'

graphql:
  tools:
      introspectionEnabled: false
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    exceptionHandlersEnabled: true

logging:
  level: 
    org.apache.kafka.clients.FetchSessionHandler: DEBUG
    org.apache.kafka.common.errors: DEBUG
  config: classpath:config/logback-spring.xml

picker:
  aiSendInterval: 1000
  aiCluster: 5
  limitClusterTime: 120
  rabbitDelay: 1000

#Redis
redis:
  host: 169.56.76.183
  port: 6379
  password: '!skcc1234'
  expireTime: 10
